# reference:
#   - https://github.com/actions/cache
#   - https://github.com/actions/checkout
#   - https://github.com/marketplace/actions/setup-miniconda

name: ci-tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  tests:
    name: "${{ matrix.session }} (py${{ matrix.python-version }} ${{ matrix.os }})"

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
        session: ["tests"]

    env:
      IRIS_TEST_DATA_VERSION: "2.17"
      ENV_NAME: "ci-tests"

    steps:
      - name: "checkout"
        uses: actions/checkout@v3

      - name: "environment configure"
        env:
          # Maximum cache period (in weeks) before forcing a cache refresh.
          CACHE_WEEKS: 2
        run: |
          echo "CACHE_PERIOD=$(date +%Y).$(expr $(date +%U) / ${CACHE_WEEKS})" >> ${GITHUB_ENV}
          echo "LOCK_FILE=requirements/ci/nox.lock/py$(echo ${{ matrix.python-version }} | tr -d '.')-linux-64.lock" >> ${GITHUB_ENV}

      - name: "data cache"
        uses: scitools/iris/.github/workflows/composite/iris-data-cache
        with:
          cache_build: 0
          env_name: ${{ env.ENV_NAME }}
          version: ${{ env.IRIS_TEST_DATA_VERSION }}
